export const MENU_ITEMS = [
  {
    state: 'dashboard',
    name: 'DASHBOARD',
    type: 'link',
    icon: 'explore',
    path: '',
  },
  {
    state: 'applicants',
    name: 'APPLICANTS',
    type: 'link',
    icon: 'supervised_user_circle',
    path: 'applicants',
  },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  // {
  //   state: 'applicants',
  //   name: 'APPLICANTS',
  //   type: 'link',
  //   icon: 'supervised_user_circle',
  //   path: 'applicants',
  // },
  //   {
  //     state: 'applicants',
  //     name: 'APPLICANTS',
  //     type: 'submenu',
  //     icon: 'layers',
  //     children: [
  //       { state: 'buttons', name: 'BUTTONS' },
  //       { state: 'cards', name: 'CARDS' },
  //       { state: 'grid', name: 'GRID' },
  //     ]
  //   },
];
